---
      
    - name: create a new ec2 key pair ,returns generated key
      ec2_key:
          aws-access_key:   "{{ aws_access_key }}"
          aws_secret_key:   "{{ aws_secret_key }}" 
          name: "{{keypair_name}}"
          region: "{{ region }}"
      register: keypair
      tags:
          - development-key
      name: copy EC2 keypair private key locally
      copy: content="{{ keypair.key.private-key }}" dest={{ ec2-key_directory}}development.pem 
      when: keypair.changed== true
      tags:
           -development-key   



     - name: Create EC2 server
       ec2:                           
         image: "{{image_name}}"
         wait: yes
         instance_type: "{{instance_type}}"
         region: "{{ region }}"
         group_id: "{{ security_group.group_id }}"
         vpc_subnet_id: "{{ my_public_subnet.subnet.id }}"
         assign_public_ip: yes
         key_name: "{{ keypair.key.name }}"
         instance_tags: 
               Name: development
         aws-access_key:   "{{ aws_access_key }}"
         aws_secret_key:   "{{ aws_secret_key }}"       
          

          
